In [1]:
import pandas as pd

In [2]:
df4 = pd.read_excel("project_data_anlytics.xlsx")
df4

,Order_id,Order_date,Status,Category,Size,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country
0,405-8078784-5731545,2022-04-30,Cancelled,Set,S,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,kurta,3XL,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN
2,404-0687676-7273146,2022-04-30,Shipped,kurta,XL,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN
3,403-9615377-8133951,2022-04-30,Cancelled,Western Dress,L,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN
4,407-1069790-7240320,2022-04-30,Shipped,Top,3XL,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49062,171-8380174-8886713,2022-04-30,Shipped - Delivered to Buyer,kurta,XL,Shipped,1,INR,318.00,secunderabad,TELANGANA,500010.0,IN
49063,403-6521026-8932351,2022-04-30,Shipped,kurta,XXL,Shipped,1,INR,362.00,NEW DELHI,DELHI,110092.0,IN
49064,408-5567953-1643519,2022-04-30,Cancelled,Set,XXL,Cancelled,0,NaN,NaN,GHAZIABAD,UTTAR PRADESH,201014.0,IN
49065,171-2038186-7698732,2022-04-30,Shipped,Set,L,Shipped,1,INR,666.00,JAMSHEDPUR,JHARKHAND,831005.0,IN
49066,403-8319151-0827544,2022-04-30,Shipped - Delivered to Buyer,Western Dress,L,Shipped,1,INR,791.00,PUDUCHERRY,PUDUCHERRY,605008.0,IN

In [35]:
df4

,Order_date,Status,Category,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country
0,2022-04-30,Cancelled,Set,Unknown,0,INR,647.620000,MUMBAI,MAHARASHTRA,400081.0,IN
1,2022-04-30,Shipped - Delivered to Buyer,kurta,Shipped,1,INR,406.000000,BENGALURU,KARNATAKA,560085.0,IN
2,2022-04-30,Shipped,kurta,Shipped,1,INR,329.000000,NAVI MUMBAI,MAHARASHTRA,410210.0,IN
3,2022-04-30,Cancelled,Western Dress,Unknown,0,INR,753.330000,PUDUCHERRY,PUDUCHERRY,605008.0,IN
4,2022-04-30,Shipped,Top,Shipped,1,INR,574.000000,CHENNAI,TAMIL NADU,600073.0,IN
...,...,...,...,...,...,...,...,...,...,...,...
49062,2022-04-30,Shipped - Delivered to Buyer,kurta,Shipped,1,INR,318.000000,secunderabad,TELANGANA,500010.0,IN
49063,2022-04-30,Shipped,kurta,Shipped,1,INR,362.000000,NEW DELHI,DELHI,110092.0,IN
49064,2022-04-30,Cancelled,Set,Cancelled,0,INR,626.003046,GHAZIABAD,UTTAR PRADESH,201014.0,IN
49065,2022-04-30,Shipped,Set,Shipped,1,INR,666.000000,JAMSHEDPUR,JHARKHAND,831005.0,IN
49066,2022-04-30,Shipped - Delivered to Buyer,Western Dress,Shipped,1,INR,791.000000,PUDUCHERRY,PUDUCHERRY,605008.0,IN

In [3]:
del df4["Order_id"]

In [8]:
del df4["Size"]

In [76]:
df4.head(15)

,Order_date,Status,Category,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country
0,2022-04-30,Cancelled,Set,Unknown,0.0,INR,647.620000,Mumbai,Maharashtra,400081.0,IN
1,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,406.000000,Bengaluru,Karnataka,560085.0,IN
2,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,329.000000,Navi mumbai,Maharashtra,410210.0,IN
3,2022-04-30,Cancelled,Western dress,Unknown,0.0,INR,753.330000,Puducherry,Puducherry,605008.0,IN
4,2022-04-30,Shipped,Top,Shipped,1.0,INR,574.000000,Chennai,Tamil nadu,600073.0,IN
5,2022-04-30,Shipped,Set,Shipped,1.0,INR,824.000000,Ghaziabad,Uttar pradesh,201102.0,IN
6,2022-04-30,Shipped,Set,Shipped,1.0,INR,653.000000,Chandigarh,Chandigarh,160036.0,IN
7,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,399.000000,Hyderabad,Telangana,500032.0,IN
8,2022-04-30,Cancelled,Set,Cancelled,0.0,INR,626.003046,Hyderabad,Telangana,500008.0,IN
9,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,363.000000,Chennai,Tamil nadu,600041.0,IN
10,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,685.000000,Chennai,Tamil nadu,600073.0,IN
11,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,364.000000,Noida,Uttar pradesh,201303.0,IN
12,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,399.000000,Amravati.,Maharashtra,444606.0,IN
13,2022-04-30,Shipped,Set,Shipped,1.0,INR,657.000000,Mumbai,Maharashtra,400053.0,IN
14,2022-04-30,Shipped - Delivered to Buyer,Set,Shipped,1.0,INR,771.000000,Mumbai,Maharashtra,400053.0,IN

In [75]:
df4.tail()

,Order_date,Status,Category,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country
49063,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,362.000000,New delhi,Delhi,110092.0,IN
49064,2022-04-30,Cancelled,Set,Cancelled,0.0,INR,626.003046,Ghaziabad,Uttar pradesh,201014.0,IN
49065,2022-04-30,Shipped,Set,Shipped,1.0,INR,666.000000,Jamshedpur,Jharkhand,831005.0,IN
49066,2022-04-30,Shipped - Delivered to Buyer,Western dress,Shipped,1.0,INR,791.000000,Puducherry,Puducherry,605008.0,IN
ship_state,NaT,NaN,NaN,Unknown,NaN,INR,626.546352,Unknown,Unknown,Unknown,IN

In [11]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49067 entries, 0 to 49066
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_date        49067 non-null  datetime64[ns]
 1   Status            49067 non-null  object
 2   Category          49067 non-null  object
 3   Courier_Status    46251 non-null  object
 4   Quanity           49067 non-null  int64
 5   currency          46068 non-null  object
 6   Amount            46068 non-null  float64
 7   ship_city         49054 non-null  object
 8   ship_state        49054 non-null  object
 9   ship_postal_code  49054 non-null  float64
 10  ship_country      49054 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 4.1+ MB

In [12]:
df4.describe()

,Order_date,Quanity,Amount,ship_postal_code
count,49067,49067.000000,46068.000000,49054.000000
mean,2022-04-15 13:46:31.032669696,0.900931,626.003046,464389.069841
min,2022-04-01 00:00:00,0.000000,0.000000,110001.000000
25%,2022-04-08 00:00:00,1.000000,432.000000,380051.000000
50%,2022-04-16 00:00:00,1.000000,568.000000,500020.000000
75%,2022-04-23 00:00:00,1.000000,771.000000,600040.000000
max,2022-04-30 00:00:00,15.000000,5584.000000,989898.000000
std,NaN,0.328271,272.738970,194769.753223

In [103]:
df4.dtypes

Order_date          datetime64[ns]
Status                      object
Category                    object
Courier_Status              object
Quanity                     object
currency                    object
Amount                     float64
ship_city                   object
ship_state                  object
ship_postal_code            object
ship_country                object
Revenue                    float64
dtype: object

In [83]:
df4.isnull().sum()

Order_date          1
Status              1
Category            0
Courier_Status      0
Quanity             1
currency            0
Amount              0
ship_city           0
ship_state          0
ship_postal_code    0
ship_country        0
dtype: int64

In [65]:
df4.loc[:,"Courier_Status"] = df4["Courier_Status"].fillna("Unknown")

In [67]:
df4.loc[:,"currency"] = df4["currency"].fillna("INR")

In [68]:
df4.loc[:,"Amount"] = df4["Amount"].fillna(df4["Amount"].mean())

In [69]:
df4.loc[:,"ship_state"] = df4["ship_state"].fillna("Unknown")

In [70]:
df4.loc[:,"ship_city"] = df4["ship_city"].fillna("Unknown")

In [71]:
df4.loc[:,"ship_postal_code"] = df4["ship_postal_code"].fillna("Unknown")

In [72]:
df4.loc[:,"ship_country"] = df4["ship_country"].fillna("IN")

In [80]:
df4.index

Index([           0,            1,            2,            3,            4,
                  5,            6,            7,            8,            9,
       ...
              49058,        49059,        49060,        49061,        49062,
              49063,        49064,        49065,        49066, 'ship_state'],
      dtype='object', length=47749)

In [82]:
df4.loc[:,"Category"] = df4["Category"].fillna("Unknown")

In [78]:
df4 = df4.drop_duplicates()

In [81]:
df4.duplicated().sum()

np.int64(0)

In [41]:
df4["Status"].unique()

array(['Cancelled', 'Shipped - Delivered to Buyer', 'Shipped',
       'Shipped - Returned to Seller', 'Shipped - Rejected by Buyer',
       'Shipped - Lost in Transit', 'Shipped - Out for Delivery',
       'Shipped - Returning to Seller', 'Shipped - Picked Up', 'Pending'],
      dtype=object)

In [84]:
df4["Category"].unique()

array(['Set', 'Kurta', 'Western dress', 'Top', 'Ethnic dress', 'Bottom',
       'Saree', 'Blouse', 'Unknown'], dtype=object)

In [43]:
df4["Courier_Status"].unique()

array(['Unknown', 'Shipped', 'Cancelled', 'Unshipped'], dtype=object)

In [50]:
df4["ship_city"].unique()

array(['Mumbai', 'Bengaluru', 'Navi mumbai', ..., 'Parasuvaikkal',
       'Baliyasan', 'Dera bassi'], dtype=object)

In [59]:
df4.loc[:,"ship_city"] = df4["ship_city"].str.strip().str.capitalize()

In [60]:
df4["ship_state"].unique()

array(['Maharashtra', 'Karnataka', 'Puducherry', 'Tamil nadu',
       'Uttar pradesh', 'Chandigarh', 'Telangana', 'Andhra pradesh',
       'Rajasthan', 'Delhi', 'Haryana', 'Assam', 'Jharkhand',
       'Chhattisgarh', 'Odisha', 'Kerala', 'Madhya pradesh',
       'West bengal', 'Nagaland', 'Gujarat', 'Uttarakhand', 'Bihar',
       'Jammu & kashmir', 'Punjab', 'Himachal pradesh',
       'Arunachal pradesh', 'Manipur', 'Goa', 'Meghalaya', 'Tripura',
       'Ladakh', 'Dadra and nagar', 'Sikkim', 'Unknown',
       'Andaman & nicobar', 'Rajshthan', 'Nl', 'Mizoram', 'New delhi',
       'Punjab/mohali/zirakpur', 'Rj', 'Orissa', 'Lakshadweep', 'Pb',
       'Apo', nan], dtype=object)

In [57]:
df4.loc[:, "ship_state"] = df4["ship_state"].str.strip().str.capitalize()

In [61]:
df4.loc[:,"Category"] = df4["Category"].str.strip().str.capitalize()

In [87]:
df4.loc[:,"Revenue"] = df4["Amount"]* df4["Quanity"]

In [108]:
df4.head(10)

,Order_date,Status,Category,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country,Revenue
0,2022-04-30,Cancelled,Set,Unknown,0.0,INR,647.620000,Mumbai,Maharashtra,400081.0,IN,0.0
1,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,406.000000,Bengaluru,Karnataka,560085.0,IN,406.0
2,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,329.000000,Navi mumbai,Maharashtra,410210.0,IN,329.0
3,2022-04-30,Cancelled,Western dress,Unknown,0.0,INR,753.330000,Puducherry,Puducherry,605008.0,IN,0.0
4,2022-04-30,Shipped,Top,Shipped,1.0,INR,574.000000,Chennai,Tamil nadu,600073.0,IN,574.0
5,2022-04-30,Shipped,Set,Shipped,1.0,INR,824.000000,Ghaziabad,Uttar pradesh,201102.0,IN,824.0
6,2022-04-30,Shipped,Set,Shipped,1.0,INR,653.000000,Chandigarh,Chandigarh,160036.0,IN,653.0
7,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,399.000000,Hyderabad,Telangana,500032.0,IN,399.0
8,2022-04-30,Cancelled,Set,Cancelled,0.0,INR,626.003046,Hyderabad,Telangana,500008.0,IN,0.0
9,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,363.000000,Chennai,Tamil nadu,600041.0,IN,363.0

In [102]:
df4["Quanity"].unique()

array(['0.0', '1.0', '2.0', '15.0', '3.0', '9.0', '13.0', '5.0', '4.0',
       '8.0', 'nan'], dtype=object)

In [101]:
df4.loc[:,"Quanity"] = df4["Quanity"].astype(str).str.strip()

In [121]:
df4.loc[:,"Quanity"] = df4["Quanity"].astype(float)

In [122]:
df4.dtypes

Order_date          datetime64[ns]
Status                      object
Category                    object
Courier_Status              object
Quanity                     object
currency                    object
Amount                     float64
ship_city                   object
ship_state                  object
ship_postal_code            object
ship_country                object
Revenue                    float64
Cost                       float64
Profit                     float64
dtype: object

In [110]:
df4.loc[:,"Cost"] = df4["Amount"] * 0.7

In [139]:
df4.head(25)

,Order_date,Status,Category,Courier_Status,Quanity,currency,Amount,ship_city,ship_state,ship_postal_code,ship_country,Revenue,Cost,Profit,category_wise_sales
0,2022-04-30,Cancelled,Set,Unknown,0.0,INR,647.620000,Mumbai,Maharashtra,400081.0,IN,0.0,453.334000,-453.334000,medium
1,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,406.000000,Bengaluru,Karnataka,560085.0,IN,406.0,284.200000,121.800000,medium
2,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,329.000000,Navi mumbai,Maharashtra,410210.0,IN,329.0,230.300000,98.700000,medium
3,2022-04-30,Cancelled,Western dress,Unknown,0.0,INR,753.330000,Puducherry,Puducherry,605008.0,IN,0.0,527.331000,-527.331000,medium
4,2022-04-30,Shipped,Top,Shipped,1.0,INR,574.000000,Chennai,Tamil nadu,600073.0,IN,574.0,401.800000,172.200000,medium
5,2022-04-30,Shipped,Set,Shipped,1.0,INR,824.000000,Ghaziabad,Uttar pradesh,201102.0,IN,824.0,576.800000,247.200000,good
6,2022-04-30,Shipped,Set,Shipped,1.0,INR,653.000000,Chandigarh,Chandigarh,160036.0,IN,653.0,457.100000,195.900000,good
7,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,399.000000,Hyderabad,Telangana,500032.0,IN,399.0,279.300000,119.700000,medium
8,2022-04-30,Cancelled,Set,Cancelled,0.0,INR,626.003046,Hyderabad,Telangana,500008.0,IN,0.0,438.202132,-438.202132,medium
9,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,363.000000,Chennai,Tamil nadu,600041.0,IN,363.0,254.100000,108.900000,medium
10,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,685.000000,Chennai,Tamil nadu,600073.0,IN,685.0,479.500000,205.500000,good
11,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,364.000000,Noida,Uttar pradesh,201303.0,IN,364.0,254.800000,109.200000,medium
12,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,399.000000,Amravati.,Maharashtra,444606.0,IN,399.0,279.300000,119.700000,medium
13,2022-04-30,Shipped,Set,Shipped,1.0,INR,657.000000,Mumbai,Maharashtra,400053.0,IN,657.0,459.900000,197.100000,good
14,2022-04-30,Shipped - Delivered to Buyer,Set,Shipped,1.0,INR,771.000000,Mumbai,Maharashtra,400053.0,IN,771.0,539.700000,231.300000,good
15,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,544.000000,Guntakal,Andhra pradesh,515801.0,IN,544.0,380.800000,163.200000,medium
16,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,329.000000,Jaipur,Rajasthan,302020.0,IN,329.0,230.300000,98.700000,medium
17,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,399.000000,New delhi,Delhi,110074.0,IN,399.0,279.300000,119.700000,medium
18,2022-04-30,Shipped - Delivered to Buyer,Kurta,Shipped,1.0,INR,458.000000,Gurgaon,Haryana,122004.0,IN,458.0,320.600000,137.400000,medium
19,2022-04-30,Shipped,Set,Shipped,1.0,INR,886.000000,Bengaluru,Karnataka,560017.0,IN,886.0,620.200000,265.800000,good
20,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,517.000000,Tiruchirappalli,Tamil nadu,620018.0,IN,517.0,361.900000,155.100000,medium
21,2022-04-30,Shipped,Set,Shipped,1.0,INR,666.000000,Bengaluru,Karnataka,560040.0,IN,666.0,466.200000,199.800000,good
22,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,376.000000,Hyderabad,Telangana,500072.0,IN,376.0,263.200000,112.800000,medium
23,2022-04-30,Cancelled,Set,Unknown,0.0,INR,570.480000,Pune,Maharashtra,411044.0,IN,0.0,399.336000,-399.336000,medium
24,2022-04-30,Shipped,Kurta,Shipped,1.0,INR,499.000000,Tezpur,Assam,784001.0,IN,499.0,349.300000,149.700000,medium

In [123]:
df4.groupby("ship_city")["Revenue"].sum().sort_values(ascending = False)

ship_city
Bengaluru              2392139.0
Hyderabad              1702870.0
Mumbai                 1529563.0
New delhi              1439977.0
Chennai                1117318.0
                         ...
Chimakurthy                  0.0
Chikmagalur                  0.0
Agra-282001                  0.0
Kotra road ,raigarh          0.0
Pampore                      0.0
Name: Revenue, Length: 4266, dtype: float64

In [125]:
df4.groupby("ship_state")["Revenue"].sum().sort_values(ascending = False)

ship_state
Maharashtra               4.690726e+06
Karnataka                 3.596661e+06
Uttar pradesh             2.427898e+06
Telangana                 2.144019e+06
Tamil nadu                2.056387e+06
Delhi                     1.571255e+06
West bengal               1.369491e+06
Kerala                    1.291669e+06
Andhra pradesh            1.078467e+06
Gujarat                   9.915902e+05
Haryana                   9.896260e+05
Rajasthan                 6.133380e+05
Madhya pradesh            5.428270e+05
Bihar                     5.388010e+05
Odisha                    4.942410e+05
Punjab                    4.671470e+05
Assam                     4.101280e+05
Uttarakhand               3.836780e+05
Jharkhand                 3.613340e+05
Goa                       2.583230e+05
Chhattisgarh              2.136080e+05
Himachal pradesh          1.824850e+05
Jammu & kashmir           1.659970e+05
Manipur                   8.806600e+04
Chandigarh                7.266200e+04
Puducherry                5.557600e+04
Andaman & nicobar         4.924000e+04
Sikkim                    4.723700e+04
Meghalaya                 4.579600e+04
Tripura                   3.776400e+04
Arunachal pradesh         3.127900e+04
Nagaland                  3.052800e+04
New delhi                 2.259800e+04
Dadra and nagar           1.584900e+04
Ladakh                    1.393300e+04
Mizoram                   1.287900e+04
Unknown                   6.319000e+03
Rajshthan                 1.126000e+03
Lakshadweep               8.250000e+02
Rj                        6.850000e+02
Orissa                    5.970000e+02
Punjab/mohali/zirakpur    5.680000e+02
Nl                        5.180000e+02
Pb                        3.990000e+02
Apo                       0.000000e+00
Name: Revenue, dtype: float64

In [126]:
df4["Revenue"].sum()

np.float64(27374140.20407745)

In [127]:
df4["Profit"].sum()

np.float64(6431663.2993625095)

In [128]:
import numpy as np

In [136]:
del df4["category_wise_sales"]

In [138]:
df4.loc[:,"category_wise_sales"] = np.where(df4["Revenue"]>600 , "good","medium")

In [140]:
df4.groupby("Category")["Revenue"].sum().sort_values(ascending = False)

Category
Set              1.479233e+07
Kurta            7.520026e+06
Western dress    2.758098e+06
Top              1.765405e+06
Ethnic dress     2.359110e+05
Blouse           1.940531e+05
Bottom           6.092100e+04
Saree            4.739400e+04
Unknown          0.000000e+00
Name: Revenue, dtype: float64

In [141]:
df4.isnull().sum()

Order_date             1
Status                 1
Category               0
Courier_Status         0
Quanity                1
currency               0
Amount                 0
ship_city              0
ship_state             0
ship_postal_code       0
ship_country           0
Revenue                1
Cost                   0
Profit                 1
category_wise_sales    0
dtype: int64

In [ ]:
df4.to_excel("project_data_anlytics.xlsx", index = False)